### ISSUE TITLE
The text on the main page is white and the background image is white

### ISSUE THREAD

**Issue by karatehammer** [karatehammer/consulting_website#19]
Which makes it hard to read.

So we either need to change the color of the text or we need to change the background image.

I'm probably looking to change the background image to something that doesn't blend into the white text.

Question for you I guess is:
What color text should someone have on their main site??

**Comment by KitchenBomber** [comment]
in progress

**Comment by KitchenBomber** [comment]
will be moving text off of image to make the page cleaner

**Comment by KitchenBomber** [comment]
Text has been effectively cleaned up
